apiVersion: v2
name: cloud-provider-equinix-metal
description: Kubernetes Cloud Provider for Equinix Metal
type: application
version: "0.1.0"
appVersion: "main"
home: https://metal.equinix.com
sources:
  - https://github.com/kubernetes-sigs/cloud-provider-equinix-metal
